spring:
  jpa:
    showSql: true
    databasePlatform: org.hibernate.dialect.H2Dialect
  datasource:
    username: sa
    password: password
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  liquibase:
    change-log: db/changelog-master.yml
    drop-first: true
springdoc:
  api-docs:
    version: openapi_3_0
    
  swagger-ui:
    enabled: true
    path: /swagger
    operations-sorter: method